### ISSUE TITLE
Irreproducible index construction

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophyle#124]
A slightly different index is constructed every time. The exact reason is not completely clear for me. We should ensure that identical indexes are constructed each time.

**Comment by karel-brinda** [comment]
Simone, could you create a unit test, which would run propagation twice and check if the resulting FASTA files are identical, please?

**Comment by simonepignotti** [comment]
Yes sure!

**Comment by karel-brinda** [comment]
To check easily if indexes are identical, we can compute md5 hashes for all index files. They should be same at every computer.

**Comment by simonepignotti** [comment]
Very good idea Karel!

**Comment by karel-brinda** [comment]
I have added logging of md5 hashes. It is currently in the devel branch. I will probably merge it to master tomorrow.

**Comment by karel-brinda** [comment]
The reason is that simplitigs may be computed slightly differently on different computers. This is not an issue of ProPhyle.
