### ISSUE TITLE
ProPhyle doesn't work on M1

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophyle#380]
See https://github.com/prophyle/prophex/issues/28

**Comment by martin-g** [comment]
Since 0.7.18 (https://github.com/lh3/bwa/commit/79b230de48c74156f9d3c26795a360fc5a2d5d3b) BWA support ARM64 architecture!
You will need to update the submodule of `bwa`.

**Comment by karel-brinda** [comment]
Thanks for the pointer!

**Comment by martin-g** [comment]
Here are the steps I used to update bwa and build ProPhyle on Linux ARM64:
- rm -rf prophyle/prophyle_index/bwa
- git submodule update --init --recursive
- cd prophyle/prophyle_index/bwa/
- git checkout 79b230de48c74156f9d3c26795a360fc5a2d5d3b
- cd -
- make -C prophyle (SUCCESS!)
- git commit -a
- git push
